# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170524_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='params',
            field=models.TextField(unique=True),
        ),
    ]
