# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170606_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='Include the protocol, example: https://www.lacity.org'),
        ),
    ]
