# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170724_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=255, verbose_name='User Name'),
        ),
    ]
