# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 03:01
from __future__ import unicode_literals

import autoslug.fields
import ckeditor_uploader.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0002_catalogrecord_dataportal_dataset_distribution_publisher_recordcolumn_spatialentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=60)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('definition', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('url_path', models.CharField(editable=False, max_length=512, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturedCatalogRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Featured Stories',
            },
        ),
        migrations.CreateModel(
            name='InterestPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('link_image', models.ImageField(blank=True, help_text='Image to link to this page', upload_to='images')),
                ('concepts', models.ManyToManyField(blank=True, to='focus.Concept')),
                ('featured_catalog_records', models.ManyToManyField(blank=True, related_name='featured_interests', through='focus.FeaturedCatalogRecord', to='datasets.CatalogRecord')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('language_code', models.CharField(max_length=10)),
                ('usage', models.CharField(choices=[('p', 'preferred'), ('a', 'alternative'), ('h', 'hidden')], max_length=1)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='focus.Concept')),
                ('scheme', models.ForeignKey(editable=False, help_text='Automatically set to the root of the concept', on_delete=django.db.models.deletion.CASCADE, related_name='scheme_labels', to='focus.Concept')),
            ],
        ),
        migrations.CreateModel(
            name='MappedUri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=500, unique=True)),
                ('sourced_meta_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focus.Concept')),
            ],
        ),
    ]
