# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('focus', '0002_auto_20170524_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='focus_conceptspluginmodel', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterModelOptions(
            name='concept',
            options={'ordering': ['path']},
        ),
        migrations.AddField(
            model_name='conceptspluginmodel',
            name='concepts',
            field=models.ManyToManyField(to='focus.Concept'),
        ),
    ]
