# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0004_auto_20170828_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestpage',
            name='order',
            field=models.IntegerField(default=0, help_text='Sets the order in which to display the page in a listing'),
        ),
        migrations.AlterField(
            model_name='interestpage',
            name='state',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='new', max_length=50),
        ),
    ]
