# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-17 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('focus', '0005_auto_20170828_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToActionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='focus_calltoactionpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True)),
                ('widget_type', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
