# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-17 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0007_calltoactionpluginmodel_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoactionpluginmodel',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
