# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-17 21:40
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('focus', '0008_auto_20171117_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetPanelAnchorsModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='focus_widgetpanelanchorsmodel', serialize=False, to='cms.CMSPlugin')),
                ('link', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], max_length=8)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='WidgetPanelModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='focus_widgetpanelmodel', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(max_length=250)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('icon', models.ImageField(upload_to='images')),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
