# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-18 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0013_auto_20171117_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimagemodel',
            name='icon',
            field=models.FileField(upload_to='uploads/icons'),
        ),
    ]
