# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 00:01
from __future__ import unicode_literals

import apps.focus.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('focus', '0014_auto_20171117_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('icon', models.FileField(upload_to='uploads/icons')),
                ('image', models.ImageField(upload_to=apps.focus.models.SimpleSlide.get_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleSlider',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='focus_simpleslider', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(help_text='For reference only', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='sliderimagemodel',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='SliderImageModel',
        ),
        migrations.AddField(
            model_name='simpleslide',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='focus.SimpleSlider'),
        ),
    ]
