# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0015_auto_20171118_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleslide',
            name='gallery',
        ),
        migrations.AddField(
            model_name='simpleslide',
            name='slider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='focus.SimpleSlider'),
            preserve_default=False,
        ),
    ]
