# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0016_auto_20171118_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleslide',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_slide', to='focus.SimpleSlider'),
        ),
    ]
