# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0017_auto_20171118_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetpanelmodel',
            name='icon',
            field=models.FileField(upload_to='uploads/icons'),
        ),
    ]
