# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-20 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('focus', '0018_auto_20171118_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityAreaHeaderModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='focus_priorityareaheadermodel', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(max_length=250)),
                ('icon', models.FileField(upload_to='uploads/icons')),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
