# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-20 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0020_contentboxmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentboxmodel',
            name='text',
            field=models.TextField(),
        ),
    ]
