# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-20 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0021_auto_20171120_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentboxmodel',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contentboxmodel',
            name='link_text',
            field=models.CharField(blank=True, help_text='If set, will be added to the end of the text field', max_length=250, null=True),
        ),
    ]
