# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 17:47
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('focus', '0023_collapsiblemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolidBoxModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='focus_solidboxmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=250)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('grey', 'Grey'), ('blue', 'Blue'), ('orange', 'Orange'), ('green', 'Green'), ('red', 'Red'), ('yelloworange', 'Yellow Orange'), ('darkblue', 'Dark Blue'), ('white', 'White'), ('black', 'Black'), ('lightgrey', 'Light Grey')], max_length=12)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
