# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-30 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0024_solidboxmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgettitlemodel',
            name='tag',
            field=models.CharField(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], default='h2', max_length=12),
        ),
    ]
