version: '2'
services:
  search:
    image: library/elasticsearch:2.4.4
    environment:
      - transport.host=127.0.0.1
      - http.host=0.0.0.0
    ports:
      - "9200:9200"
  cli:
    volumes:
      - .:/code
    depends_on:
      - db
      - search
      - cache
    env_file: .env
    environment:
      DEBUG: "1"
      #ENABLE_DEBUG_TOOLBAR: "true"
      ENABLE_DEV_EMAIL: "true"
      SEARCH_URL: elasticsearch2://search:9200/haystack
  web:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
      - search
      - cache
    env_file: .env
    environment:
      DEBUG: "1"
      #SERVE_STATIC: "true"
      #ENABLE_DEBUG_TOOLBAR: "true"
      ENABLE_DEV_EMAIL: "true"
      SEARCH_URL: elasticsearch2://search:9200/haystack
