# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 22:02
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django_fsm
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20170504_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='related',
        ),
        migrations.AlterField(
            model_name='story',
            name='datasets',
            field=models.ManyToManyField(blank=True, related_name='linked_stories', to='datasets.CatalogRecord'),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='state',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='story',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='User tags'),
        ),
    ]
