# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('stories', '0004_auto_20170512_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoriesPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='stories_storiespluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('stories', models.ManyToManyField(to='stories.Story')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
