# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_story_featured_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='storiespluginmodel',
            name='display_cards',
            field=models.BooleanField(default=False, help_text='Render linked stories as cards'),
        ),
    ]
