# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_storiespluginmodel_display_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='story',
            name='datasource_urls',
            field=models.TextField(blank=True, help_text='\n    Extra datasource urls\n    '),
        ),
    ]
