# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 21:50
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_auto_20170724_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='card_image',
            field=image_cropping.fields.ImageRatioField('featured_image', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='card image'),
        ),
        migrations.AddField(
            model_name='story',
            name='wide_card_image',
            field=image_cropping.fields.ImageRatioField('featured_image', '800x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='wide card image'),
        ),
    ]
