# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_auto_20170803_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['highlight', '-published_at'], 'verbose_name_plural': 'stories'},
        ),
        migrations.AddField(
            model_name='story',
            name='highlight',
            field=models.BooleanField(db_index=True, default=False, help_text='If checked, this story will be listed towards the top'),
        ),
    ]
