# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-10 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20170828_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryDisplayPlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-highlight', '-published_at'], 'verbose_name_plural': 'stories'},
        ),
        migrations.AddField(
            model_name='storydisplayplugin',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_display_set', to='stories.StoriesPluginModel'),
        ),
        migrations.AddField(
            model_name='storydisplayplugin',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Story'),
        ),
    ]
