# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-10 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def copy_stories(apps, schema_editor):
    StoriesPluginModel = apps.get_model('stories', 'StoriesPluginModel')
    StoryDisplayPlugin = apps.get_model('stories', 'StoryDisplayPlugin')
    for spm in StoriesPluginModel.objects.all():
        for index, story in enumerate(spm.stories.all()):
            StoryDisplayPlugin.objects.create(
                story=story,
                plugin=spm,
                order=index,
            )

class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_auto_20171010_1614'),
    ]

    operations = [
        migrations.RunPython(copy_stories),
        migrations.RemoveField(
            model_name='storiespluginmodel',
            name='stories',
        ),
        migrations.AddField(
            model_name='storiespluginmodel',
            name='stories',
            field=models.ManyToManyField(through='stories.StoryDisplayPlugin', to='stories.Story'),
        ),
    ]
