# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-17 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_copy_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storydisplayplugin',
            name='order',
            field=models.IntegerField(default=0, help_text='lower values are displayed first'),
        ),
        migrations.AlterField(
            model_name='storydisplayplugin',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_display_set', to='stories.Story'),
        ),
    ]
