# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-29 20:43
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('stories', '0013_auto_20171117_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='storydisplayplugin',
            name='sidebar_placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='story_index_sidebar', to='cms.Placeholder'),
        ),
    ]
