# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-23 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_storydisplayplugin_sidebar_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='bodyFeaturedText',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='repostPermissionLine',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
